"""recreate_all_tables

Revision ID: 3bdc3dc2a5d2
Revises: 
Create Date: 2025-02-12 00:15:10.752342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3bdc3dc2a5d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('del_005')
    with op.batch_alter_table('del_lotos_orders', schema=None) as batch_op:
        batch_op.drop_index('order_number')

    op.drop_table('del_lotos_orders')
    op.drop_table('del_manager')
    op.drop_table('del_setting_qr')
    op.drop_table('del_address_group')
    op.drop_table('del_resident_bot')
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_index('ix_photos_id')

    op.drop_table('photos')
    op.drop_table('del_setting_all')
    op.drop_table('del_setting_templates')
    op.drop_table('del_setting_type')
    op.drop_table('del_address')
    op.drop_table('del_api_key')
    op.drop_table('del_setting_storage')
    op.drop_table('del_005_admin_notifications')
    op.drop_table('del_005_bot_admins')
    with op.batch_alter_table('del_market_orders', schema=None) as batch_op:
        batch_op.drop_index('order_number')

    op.drop_table('del_market_orders')
    op.drop_table('del_setting_shop')
    op.drop_table('del_photo_order')
    op.drop_table('del_setting_unit')
    op.drop_table('del_005_bot_control')
    with op.batch_alter_table('del_claudia_orders', schema=None) as batch_op:
        batch_op.drop_index('order_number')

    op.drop_table('del_claudia_orders')
    with op.batch_alter_table('del_005_history', schema=None) as batch_op:
        batch_op.drop_index('id')

    op.drop_table('del_005_history')
    op.drop_table('del_001')
    with op.batch_alter_table('del_bot_messages', schema=None) as batch_op:
        batch_op.drop_index('message_key')

    op.drop_table('del_bot_messages')
    with op.batch_alter_table('valet_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_number', sa.String(length=10), nullable=True))
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('car_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('client_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('created', 'car_accepted', 'parked', 'return_requested', 'returning', 'completed', 'cancelled'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valet_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('created', 'car_accepted', 'parked', 'return_requested', 'returning', 'completed', 'cancelled'),
               existing_nullable=True)
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('car_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('employee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('location_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('session_number')

    op.create_table('del_bot_messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('message_text', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('del_bot_messages', schema=None) as batch_op:
        batch_op.create_index('message_key', ['message_key'], unique=True)

    op.create_table('del_001',
    sa.Column('del_001_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_001_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('del_001_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_001_sql', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('del_001_manager', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_001_api', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_001_tabl', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('del_001_id_tabl', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_001_data', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('del_001_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_005_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=50), server_default=sa.text("'0'"), nullable=False),
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_text', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('error_message', mysql.TEXT(), nullable=True),
    sa.Column('old_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('del_005_history', schema=None) as batch_op:
        batch_op.create_index('id', ['id'], unique=True)

    op.create_table('del_claudia_orders',
    sa.Column('del_claudia_order_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('del_claudia_total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_claudia_service_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_claudia_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_claudia_address_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_claudia_order_date', mysql.DATETIME(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('del_claudia_orders', schema=None) as batch_op:
        batch_op.create_index('order_number', ['del_claudia_order_number'], unique=True)

    op.create_table('del_005_bot_control',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_setting_unit',
    sa.Column('del_setting_unit_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_unit_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_unit_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_unit_value', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_unit_input', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_setting_unit_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_photo_order',
    sa.Column('del_photo_order_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_photo_order_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_photo_order_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_photo_order_id_order', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_photo_order_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_photo_order_telegram_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_photo_order_telegram_data', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('del_photo_order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('del_setting_shop',
    sa.Column('del_setting_shop_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_shop_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_shop_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_setting_shop_input', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_setting_shop_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_market_orders',
    sa.Column('del_market_order_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('del_market_total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_market_service_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_market_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_market_address_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_market_order_date', mysql.DATETIME(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('del_market_orders', schema=None) as batch_op:
        batch_op.create_index('order_number', ['del_market_order_number'], unique=True)

    op.create_table('del_005_bot_admins',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_005_admin_notifications',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_setting_storage',
    sa.Column('del_setting_storage_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_storage_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_storage_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_storage_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_storage_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('del_setting_storage_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_setting_storage_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('del_api_key',
    sa.Column('del_api_key_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_api_key_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_api_key_index', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('del_api_key_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_api_key_priority', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_api_key_date_1', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('del_api_key_date_2', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('del_api_key_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_address',
    sa.Column('del_address_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_address_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_address_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_address_floor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_address_floor_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_group', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('del_address_status_del', mysql.VARCHAR(length=1), server_default=sa.text("'0'"), nullable=True),
    sa.Column('del_address_slot', mysql.INTEGER(), server_default=sa.text("'4'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_step_2', mysql.INTEGER(unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_step_5', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_photo', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_setting_type',
    sa.Column('del_setting_type_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_type_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_type_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_setting_type_priority', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_type_input', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_setting_type_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_setting_templates',
    sa.Column('del_setting_templates_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_templates_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_show_index', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_number_print', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_tables_input', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_id_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_tables', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_tables_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_tables_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_templates_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_print', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_size', mysql.INTEGER(), server_default=sa.text("'2'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_position', mysql.INTEGER(), server_default=sa.text("'2'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_templates_tables_comment', mysql.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('del_setting_templates_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('del_setting_all',
    sa.Column('del_setting_all_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('del_setting_all_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_all_comment', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('del_setting_all_type_i_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_all_type_i_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_all_type_i_3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_all_type_i_4', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_all_type_i_5', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_all_type_t_1', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('del_setting_all_type_t_2', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('del_setting_all_type_t_3', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('del_setting_all_type_t_4', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('del_setting_all_type_t_5', mysql.VARCHAR(length=250), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('photos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('valet_session_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('photo_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('photo_type', mysql.ENUM('before', 'after'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['valet_session_id'], ['valet_sessions.id'], name='photos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.create_index('ix_photos_id', ['id'], unique=False)

    op.create_table('del_resident_bot',
    sa.Column('del_resident_bot_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_resident_bot_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_resident_bot_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_resident_bot_id_telegram', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('del_resident_bot_status_delivery', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_resident_bot_id_adress', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('del_resident_bot_step', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_resident_bot_step_try', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_step_2', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_step_5', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_address_mes_step_photo', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_resident_bot_status_auth', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_resident_bot_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('del_address_group',
    sa.Column('del_address_group_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_address_group_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_address_group_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_address_group_name2', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('del_address_group_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_setting_qr',
    sa.Column('del_setting_qr_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_setting_qr_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_setting_qr_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_setting_qr_number', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_setting_storage_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('del_setting_storage_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('del_setting_qr_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('del_manager',
    sa.Column('id_manager', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('show_manager', mysql.INTEGER(unsigned=True), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('name_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('surname_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('login_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('position_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name_ltd', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type_unit', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('access_rights_manager', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('show_manager_statistic', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('email_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phone_manager', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('color_manager', mysql.VARCHAR(length=15), server_default=sa.text("'0'"), nullable=False),
    sa.Column('access_001', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_005', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_006', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_007', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_008', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_009', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('access_stat', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Учитывать в статистики'),
    sa.Column('access_button_1', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='Сохранить и открвть новую'),
    sa.Column('telegram_id', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_bot_satatus', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_step', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_chash', mysql.VARCHAR(length=50), server_default=sa.text("'0'"), nullable=False),
    sa.Column('telegram_bot_manager_satatus', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_bot_manager_step', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('telegram_bot_manager_cache', mysql.VARCHAR(length=50), server_default=sa.text("'0'"), nullable=False),
    sa.Column('telegram_bot_update_photo_satatus', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_manager'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('del_lotos_orders',
    sa.Column('del_lotos_order_number', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('del_lotos_total_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_lotos_service_cost', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('del_lotos_status', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_lotos_address_id', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_lotos_order_date', mysql.DATETIME(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    with op.batch_alter_table('del_lotos_orders', schema=None) as batch_op:
        batch_op.create_index('order_number', ['del_lotos_order_number'], unique=True)

    op.create_table('del_005',
    sa.Column('del_005_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('del_005_show', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('del_005_code', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('del_005_phone_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('del_005_number', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_005_shop', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_unit', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_status_notification', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('del_005_type', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_address', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_storage', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_qr', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_comment', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('del_005_name_client', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('del_005_manager_1', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_manager_2', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_manager_3', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('del_005_data_1', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('del_005_data_2', mysql.DATETIME(), nullable=True),
    sa.Column('del_005_data_3', mysql.DATETIME(), nullable=True),
    sa.Column('del_005_data_4', mysql.DATETIME(), nullable=True),
    sa.Column('del_005_data_5', mysql.DATETIME(), nullable=True),
    sa.Column('del_005_data_6', mysql.DATETIME(), nullable=True),
    sa.Column('del_005_photo_1', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('del_005_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
